name: dymaxion_clock
description: Dymaxion clock.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

flutter:
  uses-material-design: true
